### ISSUE TITLE
error with Beta

### ISSUE THREAD

**Issue by violafanfani** [sottorivalab/midaa#3]
I am trying to run MIIDA and I am following your tutorials. Until yesterday I was using only two inputs with `likelihoods = ["G","P"]` and wverything was working fine. Now I introduced a dataset with a Beta distribution (`likelihoods = ["G","P","Beta"]`).  When I run  maa.fit_MIDAA() I get this error: 
```
TypeError: param() got an unexpected keyword argument 'constraints'
```

It appears it is linked to this line here: 

https://github.com/sottorivalab/midaa/blob/be8ad48cfde8e6f1e3a50a4a079e3f6946e6cb34/src/midaa/Utils_guide.py#L43

I tried to do the same with `likelihoods = ["G","P","G"]` and although it is conceptually wrong, the error is solved, which makes sense since the constrainst parameter is passed only onto Beta. 

Can you help me solve this?

**Comment by violafanfani** [comment]
After checking the code better, it looks like the issue is that the pyro.param is called with a `constraints` parameter instead of `constraint`. It seems to be working on my side, can you check if that is indeed the solution?

**Comment by Militeee** [comment]
Hi @violafanfani, I'm sorry. I just now realized that I have problems with the automatic emails from GitHub and completely lost this 🥲 
Thanks a lot for spotting the bug, I am making a major debugging effort before publication so if you spot something else just let me know, I will be faster for sure this time.
